name: ask2receive
description: A Flutter app for daily affirmations with notifications.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.5
  timezone: ^0.10.0
  http: ^1.2.2
  url_launcher: ^6.1.14
  # flutter_email_sender: ^6.0.3
  flutter_time_picker_spinner: ^2.0.0
  intl: ^0.20.1
  provider: ^6.0.2
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^11.3.1
  meta: any
  petitparser: any
  characters: any
  collection: any
  material_color_utilities: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/Ask2Receive_Logo.png" # Path to your app icon

flutter:
  assets:
    - assets/img/Ask2Receive_Logo.png
    - assets/img/galaxy_background.png
    - assets/data/affirmations.txt
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
